[package]
name = "simple_db"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlparser = "0.56"
lazy_static = "1.5"
bincode = "2.0"
clap = { version = "4.5", features = ["derive"] }
rustyline = "15.0"
rayon = "1.10"
